---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- poddisruptionbudget.yaml
- serviceaccount-registry.yaml
- serviceaccount-nifi.yaml
- secret-nifi-registry-config.yaml
- configmap-nifi-config.yaml
- service-registry.yaml
- service-zookeeper.yaml
- service-nifi-headless.yaml
- service-nifi.yaml
- service-nifi-metrics.yaml
- ss-nifi-registry.yaml
- ss-nifi-zookeeper.yaml
- ss-nifi.yaml
- route-nifi.yaml



commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: "nifi"

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: nifi-config
    envs:
      - params.env

vars:
  - name: s3_endpoint_url
    objref:
      name: trino-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.s3_endpoint_url
  - name: s3_endpoint_url_prefix
    objref:
      name: trino-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.s3_endpoint_url_prefix
  - name: s3_credentials_secret
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: trino-config
    fieldref:
      fieldpath: data.s3_credentials_secret
  - name: trino_environment
    objref:
      kind: ConfigMap
      apiVersion: v1
      name: trino-config
    fieldref:
      fieldpath: data.trino_environment
  - name: trino_db_secret
    objref:
      name: trino-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.trino_db_secret
  - name: hive_metastore_cpu_request
    objref:
      name: trino-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.hive_metastore_cpu_request
  - name: hive_metastore_cpu_limit
    objref:
      name: trino-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.hive_metastore_cpu_limit
  - name: hive_metastore_memory_request
    objref:
      name: trino-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.hive_metastore_memory_request
  - name: hive_metastore_memory_limit
    objref:
      name: trino-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.hive_metastore_memory_limit
  - name: trino_cpu_request
    objref:
      name: trino-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.trino_cpu_request
  - name: trino_cpu_limit
    objref:
      name: trino-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.trino_cpu_limit
  - name: trino_memory_request
    objref:
      name: trino-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.trino_memory_request
  - name: trino_memory_limit
    objref:
      name: trino-config
      apiVersion: v1
      kind: ConfigMap
    fieldref:
      fieldpath: data.trino_memory_limit

configurations:
  - params.yaml

images:
  - name: busybox
    newName: busybox
    newTag: 1.34.0
  - name: alpine
    newName: alpine
    newTag: 3.13.6
  - name: nifi
    newName: apache/nifi
    newTag: 1.14.0
  - name: nifi-registry
    newName: apache/nifi-registry
    newTag: 1.14.0
  - name: zookeeper
    newName: bitnami/zookeeper
    newTag: 3.7.0-debian-10-r179

