---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - poddisruptionbudget.yaml
  - serviceaccount-registry.yaml
  - serviceaccount-nifi.yaml
  - scc.yaml
  - configmap-nifi-config.yaml
  - service-registry.yaml
  - service-nifi-zookeeper-headless.yaml
  - service-nifi-zookeeper.yaml
  - service-nifi-headless.yaml
  - service-nifi.yaml
  - service-nifi-metrics.yaml
  - ss-nifi-registry.yaml
  - ss-nifi-zookeeper.yaml
  - ss-nifi.yaml
  - route-nifi.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: "nifi"

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: parameters
    envs:
      - params.env
vars:
  - name: namespace
    objref:
      kind: ConfigMap
      name: parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.namespace
  - name: storage_class
    objref:
      kind: ConfigMap
      name: parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.storage_class

configurations:
  - params.yaml

images:
  - name: busybox
    newName: busybox
    newTag: 1.34.0
  - name: alpine
    newName: alpine
    newTag: 3.13.6
  - name: nifi
    newName: apache/nifi
    newTag: 1.13.2
  - name: nifi-registry
    newName: apache/nifi-registry
    newTag: 1.13.2
  - name: zookeeper
    newName: bitnami/zookeeper
    newTag: 3.7.0-debian-10-r179
