---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: route-reencryptor-sa
  labels:
    app: route-reencryptor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: route-reencryptor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: route-reencryptor
subjects:
  - kind: ServiceAccount
    name: route-reencryptor-sa
    namespace: nifi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route-reencryptor
rules:
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
