---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: route-reencrypt-binding
  namespace: nifi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: route-reencrypt-role
subjects:
- kind: ServiceAccount
  name: nifi-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: route-reencrypt-role
  namespace: nifi
rules:
- apiGroups:
  - ""
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - get
  - list
  - update
  - patch
  - replace
