---
apiVersion: v1
kind: Service
metadata:
  name: nifi-registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: nifi
    app.kubernetes.io/version: "1.13.2"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: nifi
