---
# Source: nifi/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nifi-headless
  labels:
    app: "nifi"
    chart: "nifi-0.7.9"
    release: "nifi"
    heritage: "Helm"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8080
    name: http
  - port: 6007
    name: cluster
  selector:
    app: "nifi"
    release: "nifi"