---
apiVersion: v1
kind: Service
metadata:
  name: nifi-zookeeper
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: nifi
    app.kubernetes.io/component: zookeeper
spec:
  type: ClusterIP
  ports:
    - name: tcp-client
      port: 2181
      targetPort: client
    - name: follower
      port: 2888
      targetPort: follower
    - name: tcp-election
      port: 3888
      targetPort: election
  selector:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: nifi
    app.kubernetes.io/component: zookeeper
